server:
  port: 8080

business-central:
  oauth2:
    token-uri: https://login.microsoftonline.com/235ce906-04c4-4ee5-a705-c904b1fa3167/oauth2/v2.0/token
    grant-type: client_credentials
    scope: https://api.businesscentral.dynamics.com/.default
    client-id: 015168df-815c-4246-aed3-aacaf1b9f20a
    client-secret: ${BC_CLIENT_SECRET}
    tenant-id: 235ce906-04c4-4ee5-a705-c904b1fa3167
  api:
    base-url: https://api.businesscentral.dynamics.com/v2.0/235ce906-04c4-4ee5-a705-c904b1fa3167/Plexus/api/NEL/AcessPurchasesAPI/v2.0/companies(683ADB98-EA07-F111-8405-7CED8D83AA60)
